language: node_js

services:
  - docker

node_js:
  - "8"

addons:
  chrome: stable

before_script:
      - "sudo chown root /opt/google/chrome/chrome-sandbox"
      - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test-headless
#  - docker pull kaitoedter/chatty
#  - npm run e2e-headless
